version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres-db'
    environment:
      - 'POSTGRES_DB=adnd'
      - 'POSTGRES_PASSWORD=adnd'
      - 'POSTGRES_USER=adnd'
    ports:
      - '5432:5432'

  app:
    depends_on:
      - postgres
    build: .
    image: 'avanade-adnd'
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.main.allow-bean-definition-overriding" : "true",
        "spring.datasource.url"  : "jdbc:postgresql://postgres-db:5432/adnd",
        "spring.datasource.username" : "adnd",
        "spring.datasource.password" : "adnd",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "create",
        "spring.jpa.properties.hibernate.jdbc.batch_size" : "50",
        "spring.sql.init.continue-on-error" : "true"
      }'
    ports:
      - 9080:9080

