server:
  servlet:
    context-path: /
  port: 9080
  compression:
    mime-types:
    - application/json

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/adnd
    username: adnd
    password: adnd

  application:
    name: store-ms
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format-sql: true
  sql:
    init:
      continue-on-error: true
